### ISSUE TITLE
Change behavior of TranslatableInterface::__toString() for Drupal compatibility

### ISSUE THREAD

**Issue by TravisCarden** [php-tuf/composer-stager#179]
The current behavior of `TranslatableInterface::__toString()` conflicts with Drupal:

> This requirement of `TranslatableInterface::__toString()` is incompatible with Drupal's `TranslatableMarkup`, because Drupal's `TranslatableMarkup::__toString()` returns the translated string (it basically does the same as `trans()`).
>
> Can we change this Composer Stager interface so that instead of defining `__toString()` we define a different method (e.g., `noTrans()`) to return the string in its original language? This can be deferred to a followup issue instead of blocking an initial merge of this PR.
>
> _Originally posted by @effulgentsia in https://github.com/php-tuf/composer-stager/pull/141#discussion_r1220513275_

A solution is not yet specified. Consider alternatives.

**Comment by effulgentsia** [comment]
I thought some more about this. The key feature that Drupal needs is to be able to translate exception messages differently than UI messages. Perhaps the most natural way to express this is to use the $domain parameter? In other words, for TranslatableInterface objects that Composer Stager creates when throwing an exception, can Composer Stager pass `domain: 'exception'` (TBD: or `'exceptions'`?, or `'exception-messages'`?, or `'messages.exception'`?)?  Then `TranslatableExceptionTrait` instead of calling `(string) $translatableMessage` can call `$translatableMessage->trans()` and leave it to the translator to decide how to translate exception messages.

Which then means we can remove `TranslatableInterface::__toString()` entirely.

**Comment by effulgentsia** [comment]
I created https://www.drupal.org/project/automatic_updates/issues/3368808 for implementing the Drupal-side of this once this Composer Stager issue is resolved.

**Comment by TravisCarden** [comment]
Thanks, @effulgentsia; I like that proposal! I've created https://github.com/php-tuf/composer-stager/pull/196 for the first part--using an `exceptions` domain for translatable exception messages.

**Comment by TravisCarden** [comment]
Done, @effulgentsia! 🙂️

**Comment by wimleers** [comment]
Per https://www.drupal.org/project/automatic_updates/issues/3368808#comment-15132239, can we get an `alpha3`? 🙏

**Comment by TravisCarden** [comment]
Here you go, @wimleers: https://github.com/php-tuf/composer-stager/releases/tag/v2.0.0-alpha3. I'm afraid, as you'll see from the release notes, it's a bit of a doozy--lots of namespace reorganization.
