### ISSUE TITLE
Do and automate performance testing

### ISSUE THREAD

**Issue by TravisCarden** [php-tuf/composer-stager#68]
With the addition of all the new preconditions in https://github.com/php-tuf/composer-stager/issues/58, we'll be scanning the filesystem a lot. But we don't know what the performance impact will be, especially on large codebases, because we haven't done any testing.

### Proposal

I think we need do some initial benchmarking and create a CI job that lets us watch the numbers over time. Depending on what we find, we can determine whether we need to optimize.

### Follow-up

For posterity, here are some ideas for optimization _if our testing shows we need it_:

- https://github.com/php-tuf/composer-stager/issues/75 so cheaper preconditions can be evaluated first.
- Add Unix `find`-based file finders (with a fallback strategy like we did with `rsync`).
- Cache filesystem scan results for reuse between preconditions within the same PHP process.
- Cache whole precondition check results _beyond_ single PHP processes, with cache expiration/invalidation.
- Run precondition checks concurrently, i.e., multithreaded.

**Comment by wimleers** [comment]
> Cache filesystem scan results for reuse between preconditions within the same PHP process.

Is this necessary? That'd cause significant increase in memory consumption, and it'd increase linearly with the complexity of the site (i.e. more packages = more files) 😅

Isn't the fact that [`stat()`](https://www.php.net/manual/en/function.stat.php) (and `lstat()`) is cached already enough? See the [`clearstatcache()`](https://www.php.net/manual/en/function.clearstatcache.php) docs for details.

I think a single `clearstatcache()` prior to evaluating the children of `NoUnsupportedLinksExist` would be sufficient to guarantee up-to-date results at all times?

> Cache whole precondition check results beyond single PHP processes, with cache expiration/invalidation.

Not only would this be a huge amount of complexity to manage … but how could this possibly handle cache invalidation? You'd have to rely on `inotify` on Linux, `FSEvents` on macOS etc. (I know because I once built something on top of these: https://github.com/wimleers/fileconveyor.)

> Run precondition checks concurrently, i.e., multithreaded.

Did PHP add multithreading support I do not know about? 😅

**Comment by TravisCarden** [comment]
Thanks for the thoughts, @wimleers. Let's save them for later. Those issues were explicitly deferred to follow-ups _"if our testing shows we need it"_. Per the issue title and proposal, this is scoped at getting some initial performance data and automating ongoing scans.

**Comment by TravisCarden** [comment]
Adding this as a prerequisite for https://github.com/php-tuf/composer-stager/milestone/1 per @effulgentsia

**Comment by wimleers** [comment]
Why was this removed from the `v2.0.0` milestone on March 21? (I'd like to understand the rationale.)

**Comment by effulgentsia** [comment]
The thinking was that even if some refactoring of the preconditions ends up being needed that it can be done without breaking APIs, so could be done in 2.1 or 2.2.
